### ISSUE TITLE
Treatment of SVGs

### ISSUE THREAD

**Issue by alexpainter** [tabanliviu/image-checker#10]
SVGs are being higlighted in red when they should perhaps be excluded?
![imagecheckersvg](https://cloud.githubusercontent.com/assets/5479712/25440075/3499806c-2a96-11e7-82cf-8ed8fef8ba77.png)

**Comment by tabanliviu** [comment]
@alexpainter I think svgs by definition should have coverage 100%

**Comment by simonhearne** [comment]
Detecting SVGs is tough, I believe that we have no access to the mimetype?
We would need to have string checks to identify SVGs: name contains '.svg' or '<svg' or 'image/svg'.
Then do we treat them as 100% coverage, or ignore them altogether?

**Comment by simonhearne** [comment]
Here's another test case:
See <https://responsiveimages.org/demos/>. This page has a repeating background image in base64 encoded SVG.

![image](https://cloud.githubusercontent.com/assets/496189/25894819/5330e49a-3575-11e7-8ce8-75a8b08d07bd.png)

**Comment by simonhearne** [comment]
Here's a more serious issue on <http://www.bbc.co.uk/news/>:
![image](https://cloud.githubusercontent.com/assets/496189/25902187/c4ba6152-3590-11e7-977d-740bbd7dce89.png)
