### ISSUE TITLE
Extension is unusable until the page loads

### ISSUE THREAD

**Issue by simonhearne** [tabanliviu/image-checker#28]
On slower pages such as <http://www.dailymail.co.uk/home/index.html> it is quite likely that a user will click on the extension before the page completes loading. In this case there is no Start button and no indication why. The start button does not appear when the page does load, giving the impression that the extension is broken.

**Comment by tabanliviu** [comment]
The issue is that the content script of the extension is added on document_idle to not interfere with the page. https://developer.chrome.com/extensions/content_scripts#run_at

**Comment by tabanliviu** [comment]
@simonhearne is this an issue? please prioritize or close

**Comment by simonhearne** [comment]
Yes, we should at least have a 'please wait while the page loads...' message, then load the button asap.
