### ISSUE TITLE
When the route is changed by javascript, the image-checker is not re-triggered.

### ISSUE THREAD

**Issue by robertdumitrescu** [tabanliviu/image-checker#31]
For instance on this site: (http://www.vebleno.com/) if I activate the image-efficiency-checker and I go on any other route by clicking on the gray bars, the plugin doesn't re-check the currently displayed images.

Screenshot:

![screenshot from 2017-05-11 14-44-43](https://cloud.githubusercontent.com/assets/10505774/25952406/7b7d43ce-3658-11e7-8e6a-8fb9cc75f2f4.png)

**Comment by simonhearne** [comment]
This is true of resize events and still events too. I suggest we use the resize and mutation observer event listeners to trigger the script to rerun.

**Comment by tabanliviu** [comment]
fixed in 1.4.0
