### ISSUE TITLE
Add analytics opt-out?

### ISSUE THREAD

**Issue by simonhearne** [tabanliviu/image-checker#32]
Not all users of the extension will be happy to share their data with NCC Group via Google Analytics. Should we provide an opt-out of analytics collection within popup.html?
<https://twitter.com/soulislove/status/862348312330076160>
![image](https://cloud.githubusercontent.com/assets/496189/25993592/55399460-3702-11e7-8d2a-24ce180749d9.png)

**Comment by simonhearne** [comment]
@tabanliviu can we put this in the extension options? How much work would that be?

**Comment by tabanliviu** [comment]
fixed in 1.4.0
