### ISSUE TITLE
Doesn't account for device DPR?

### ISSUE THREAD

**Issue by igrigorik** [tabanliviu/image-checker#45]
![image](https://user-images.githubusercontent.com/10652/27781577-c1233b32-5fce-11e7-93e9-40789f818840.png)

**Comment by tabanliviu** [comment]
Thanks for reporting this. I'll try and get a fix in for the 1.5.0 release

**Comment by tabanliviu** [comment]
I've made the coverage calculation take into account device pixel ratio as well as displaying the current device pixel ratio in each overlay to make it even more clear how the value is calculated
