### ISSUE TITLE
Add copyright statements to source code

### ISSUE THREAD

**Issue by andydavies** [tabanliviu/image-checker#8]

**Comment by tabanliviu** [comment]
@andydavies can you please provide the copy needed in all source files? thanks

**Comment by tabanliviu** [comment]
@simonhearne can you please provide the copy needed in all source files? thanks
I've got rights to push code so I'd like to finish this and release #9 as well

**Comment by jamiecoombs** [comment]
@andydavies: it doesn't really make sense to add copyright statements to the code when we are releasing the code under the apache2 licence. A copyright statement would indicate that we are not willing for third parties to copy/modify the code. Please can you clarify what you mean.

**Comment by jamiecoombs** [comment]
@andydavies: ignore me! @ashvince has just pointed out that we simply need to copy the boilerplate from the Appendix of LICENSE.md to each of the source files.
